const List<String> timeZones = [
  "Pacific Time (PT) UTC -8 / UTC -7",
  "Mountain Time (MT) UTC -7 / UTC -6",
  "Central Time (CT) UTC -6 / UTC -5",
  "Eastern Time (ET) UTC -5 / UTC -4",
  "Brasilia Time (BRT) UTC -3",
  "Argentina Time (ART) UTC -3",
  "Colombia Time (COT) UTC -5",
  "Greenwich Mean Time (GMT) UTC 0",
  "Central European Time (CET) UTC +1 / UTC +2",
  "Eastern European Time (EET) UTC +2 / UTC +3",
  "West Africa Time (WAT) UTC +1",
  "Central Africa Time (CAT) UTC +2",
  "East Africa Time (EAT) UTC +3",
  "India Standard Time (IST) UTC +5:30",
  "China Standard Time (CST) UTC +8",
  "Japan Standard Time (JST) UTC +9",
  "Singapore Time (SGT) UTC +8",
  "Gulf Standard Time (GST) UTC +4",
  "Arabian Standard Time (AST) UTC +3",
  "Australian Western Standard Time (AWST) UTC +8",
  "Australian Eastern Standard Time (AEST) UTC +10 / UTC +11",
  "New Zealand Standard Time (NZST) UTC +12 / UTC +13"
];

const List<String> listPlatforms = [
  "LinkedIn",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Stack Overflow",
  "HackerRank",
  "Dribbble",
  "Behance",
  "Figma Community",
  "Adobe Portfolio",
  "Medium",
  "Substack",
  "WordPress",
  "Ghost",
  "500px",
  "DeviantArt",
  "Flickr",
  "YouTube",
  "Vimeo",
  "Twitch",
  "Kaggle",
  "Tableau Public",
  "Google Colab",
  "About.me",
  "AngelList"
];

const List<String> listRegions = [
  'APAC',
  'North-America',
  'EMEA',
  'GULF',
  'LATAM',
];

const List<String> listDepartments = [
  "Artificial Intelligence (AI) & Machine Learning",
  "Business Development",
  "Cloud Computing",
  "Content Creation & Copywriting",
  "Corporate Social Responsibility (CSR)",
  "Customer Success",
  "Customer Support",
  "Cybersecurity",
  "Data Science & Analytics",
  "E-commerce",
  "Education & Training",
  "Environmental, Health & Safety (EHS)",
  "Event Management",
  "Finance",
  "GIS",
  "Healthcare & Medical Affairs",
  "HR",
  "Internal Audit",
  "International Expansion",
  "IT Support & Infrastructure",
  "Legal & Compliance",
  "Logistics & Warehouse",
  "Maintenance & Engineering",
  "Marketing",
  "Non-Profit Management",
  "Operations & Administration",
  "Procurement & Supply Chain",
  "Product Management",
  "Production & Manufacturing",
  "Quality Assurance (QA) & Testing",
  "Quality Control",
  "Real Estate & Facilities",
  "Research & Development (R&D)",
  "Retail Operations",
  "Sales",
  "Software Development",
  "Sustainability & ESG",
  "UI/UX Design",
  "User Acquisition"
];

const Map<String, List<String>> mapSkillsSelection = {
  "Artificial Intelligence (AI) & Machine Learning": [
    "Neural Networks",
    "Computer Vision",
    "Natural Language Processing (NLP)",
    "Reinforcement Learning",
    "Model Deployment",
    "AI Ethics",
    "TensorFlow/PyTorch"
  ],
  "Business Development": [
    "Lead Generation",
    "Market Research",
    "Strategic Partnerships",
    "B2B Sales",
    "Negotiation",
    "Client Relationship Management",
    "Revenue Growth Strategies",
    "Go-to-Market Strategy",
    "Competitive Analysis",
    "Sales Funnel Optimization"
  ],
  "Cloud Computing": [
    "AWS",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Serverless Computing",
    "Cloud Security",
    "Infrastructure as Code (IaC)",
    "Kubernetes Orchestration",
    "Hybrid Cloud Management",
    "Cloud Migration Strategies"
  ],
  "Content Creation & Copywriting": [
    "SEO Writing",
    "Scriptwriting",
    "Blogging",
    "Technical Writing",
    "Editing & Proofreading",
    "Content Strategy",
    "CMS Tools (WordPress)"
  ],
  "Corporate Social Responsibility (CSR)": [
    "Community Engagement",
    "Philanthropy Strategy",
    "Employee Volunteering",
    "Sustainability Partnerships",
    "CSR Reporting",
    "Ethical Sourcing",
    "CSR Analyst",
  ],
  "Customer Success": [
    "Onboarding Strategies",
    "Customer Retention",
    "Churn Reduction",
    "SaaS Metrics (ARR, NRR)",
    "Customer Health Scoring",
    "Success Plans"
  ],
  "Customer Support": [
    "Communication Skills",
    "Problem-Solving",
    "Conflict Resolution",
    "Product Knowledge",
    "Empathy",
    "Active Listening",
    "Time Management",
    "Multilingual Support",
    "Zendesk/Intercom",
    "Customer Feedback Analysis"
  ],
  "Cybersecurity": [
    "Penetration Testing",
    "Network Security",
    "Incident Response",
    "Ethical Hacking",
    "Data Privacy",
    "Risk Assessment",
    "Security Auditing",
    "Threat Intelligence",
    "SIEM Tools",
    "IAM (Identity & Access Management)"
  ],
  "Data Science & Analytics": [
    "Data Cleaning",
    "Machine Learning",
    "Statistical Analysis",
    "Data Visualization",
    "Big Data Technologies",
    "SQL & NoSQL",
    "Predictive Analytics",
    "Natural Language Processing (NLP)",
    "Deep Learning (TensorFlow/PyTorch)",
    "A/B Testing Analysis"
  ],
  "E-commerce": [
    "Shopify/Magento Management",
    "Payment Gateway Integration",
    "Omnichannel Strategy",
    "Cart Abandonment Solutions",
    "Dropshipping",
    "Conversion Rate Optimization"
  ],
  "Education & Training": [
    "Curriculum Design",
    "E-Learning Development",
    "Workshop Facilitation",
    "Learning Management Systems (LMS)",
    "Assessment Design",
    "Instructional Design"
  ],
  "Environmental, Health & Safety (EHS)": [
    "OSHA Compliance",
    "Risk Assessments",
    "Incident Investigation",
    "Waste Management",
    "Sustainability Reporting",
    "Emergency Response Planning"
  ],
  "Event Management": [
    "Vendor Coordination",
    "Budget Management",
    "Event Promotion",
    "Virtual Event Platforms",
    "Logistics Planning",
    "Post-Event Analysis"
  ],
  "Finance": [
    "Financial Analysis",
    "Budgeting",
    "Accounting",
    "Investment Management",
    "Risk Assessment",
    "Tax Planning",
    "Auditing",
    "Financial Reporting",
    "Mergers & Acquisitions",
    "FP&A (Financial Planning & Analysis)",
    "ERP Systems (SAP/Oracle)"
  ],
  "GIS": ["GIS Analyst", "GIS Consultant", "GIS Senior Manager"],
  "Healthcare & Medical Affairs": [
    "Clinical Trials",
    "Regulatory Affairs",
    "Medical Writing",
    "Patient Advocacy",
    "Pharmacovigilance",
    "Healthcare Compliance"
  ],
  "HR": [
    "Recruitment",
    "Onboarding",
    "Training & Development",
    "Performance Management",
    "HR Policies & Compliance",
    "Employee Relations",
    "Compensation & Benefits",
    "Talent Acquisition",
    "Succession Planning",
    "Diversity & Inclusion",
    "HR Analytics",
    "Workforce Planning",
    "HRIS (Workday/SAP)"
  ],
  "Internal Audit": [
    "SOX Compliance",
    "Process Auditing",
    "Fraud Detection",
    "Risk Mitigation",
    "Audit Reporting",
    "Data Analytics for Audits"
  ],
  "International Expansion": [
    "Market Entry Strategies",
    "Localization",
    "Cross-Cultural Negotiation",
    "Global Compliance",
    "International Tax Planning",
    "Regional Partnership Building"
  ],
  "IT Support & Infrastructure": [
    "Network Administration",
    "System Security",
    "Technical Support",
    "Hardware Maintenance",
    "Software Installation",
    "Data Backup & Recovery",
    "Virtualization (VMware)",
    "ITIL Framework",
    "Disaster Recovery Planning"
  ],
  "Legal & Compliance": [
    "Contract Law",
    "Regulatory Compliance",
    "Intellectual Property",
    "Litigation",
    "Corporate Law",
    "Risk Management",
    "Legal Research",
    "GDPR Compliance",
    "Anti-Money Laundering (AML)",
    "Contract Negotiation"
  ],
  "Logistics & Warehouse": [
    "Inventory Management",
    "Supply Chain Coordination",
    "Warehouse Operations",
    "Fleet Management",
    "Distribution Planning",
    "Logistics Optimization",
    "RFID Technology",
    "Last-Mile Delivery",
    "Cold Chain Management"
  ],
  "Maintenance & Engineering": [
    "Equipment Maintenance",
    "Troubleshooting",
    "Mechanical & Electrical Engineering",
    "Safety Compliance",
    "Preventive Maintenance",
    "Predictive Maintenance",
    "CAD Software",
    "PLC Programming"
  ],
  "Marketing": [
    "Content Marketing",
    "SEO & SEM",
    "Social Media Management",
    "Email Marketing",
    "Market Analysis",
    "Brand Management",
    "Public Relations",
    "Digital Advertising",
    "Influencer Marketing",
    "Video Marketing (TikTok/YouTube)",
    "Marketing Analytics (Google Analytics)",
    "Customer Segmentation",
    "CRM Tools (HubSpot/Salesforce)"
  ],
  "Non-Profit Management": [
    "Grant Writing",
    "Donor Relations",
    "Fundraising Campaigns",
    "Volunteer Coordination",
    "Impact Measurement",
    "Advocacy Strategies"
  ],
  "Operations & Administration": [
    "Process Improvement",
    "Workflow Optimization",
    "Resource Allocation",
    "Project Coordination",
    "Office Management",
    "Compliance & Reporting",
    "Six Sigma/Lean",
    "Vendor Management",
    "Operational Risk Management"
  ],
  "Procurement & Supply Chain": [
    "Vendor Management",
    "Logistics Coordination",
    "Inventory Management",
    "Supply Chain Optimization",
    "Cost Control",
    "Procurement Negotiation",
    "Demand Forecasting",
    "Supplier Risk Management",
    "ERP Integration"
  ],
  "Product Management": [
    "Market Research",
    "Agile Methodologies",
    "Product Roadmap Planning",
    "User Research",
    "Prototyping",
    "Business Strategy",
    "Stakeholder Management",
    "A/B Testing",
    "Product Lifecycle Management",
    "KPI Tracking",
    "Competitor Benchmarking"
  ],
  "Production & Manufacturing": [
    "Process Automation",
    "Lean Manufacturing",
    "Production Scheduling",
    "Quality Control",
    "Supply Chain Management",
    "Six Sigma",
    "3D Printing/Additive Manufacturing",
    "ERP for Manufacturing"
  ],
  "Quality Assurance (QA) & Testing": [
    "Automated Testing",
    "Manual Testing",
    "Test Case Design",
    "Performance Testing",
    "Bug Tracking",
    "Security Testing",
    "Regression Testing",
    "Selenium/Cypress",
    "Load Testing",
    "API Testing (Postman)"
  ],
  "Quality Control": [
    "Inspection Procedures",
    "ISO Standards",
    "Statistical Process Control",
    "Failure Analysis",
    "Risk Management",
    "Continuous Improvement",
    "Root Cause Analysis",
    "Calibration Techniques",
    "Quality Management Systems (QMS)"
  ],
  "Real Estate & Facilities": [
    "Property Management",
    "Lease Negotiation",
    "Space Planning",
    "Facility Maintenance",
    "Sustainability Certifications (LEED)",
    "Capital Improvement Projects"
  ],
  "Research & Development (R&D)": [
    "Innovative Thinking",
    "Prototyping",
    "Data Analysis",
    "Market Research",
    "Technical Writing",
    "Testing & Validation",
    "Patent Filing",
    "Cross-functional Collaboration",
    "Experimental Design"
  ],
  "Retail Operations": [
    "Merchandising",
    "Store Layout Optimization",
    "Loss Prevention",
    "POS Systems",
    "Customer Experience Design",
    "Retail Analytics"
  ],
  "Sales": [
    "Lead Generation",
    "Customer Relationship Management",
    "Sales Strategy",
    "Negotiation",
    "Closing Deals",
    "Product Knowledge",
    "Territory Management",
    "Sales Forecasting",
    "CRM Software (Salesforce/Zoho)",
    "Account Management",
    "Sales Enablement Tools"
  ],
  "Software Development": [
    "Android Development",
    "iOS Development",
    "Flutter Development",
    "React Native Development",
    "Web Development",
    "Mobile App Development",
    "Web App Development",
    "DevOps",
    "Database Management",
    "Cloud Computing",
    "Backend Development (Node.js/Python/Java)",
    "Frontend Development (React/Angular/Vue)",
    "Game Development",
    "Embedded Systems",
    "Blockchain Development",
    "API Development",
    "Microservices Architecture",
    "CI/CD Pipelines",
    "Containerization (Docker/Kubernetes)"
  ],
  "Sustainability & ESG": [
    "Carbon Footprint Analysis",
    "ESG Reporting",
    "Renewable Energy Projects",
    "Circular Economy",
    "Stakeholder Engagement",
    "Sustainability Audits",
    "Sustainability Analyst",
    "Manager",
    "ESG Consultant"
  ],
  "UI/UX Design": [
    "User Research",
    "Wireframing & Prototyping",
    "Interaction Design",
    "Visual Design",
    "Usability Testing",
    "Typography & Color Theory",
    "Figma & Adobe XD",
    "Accessibility Design",
    "Responsive Design",
    "Motion Design",
    "Design Systems"
  ],
  "User Acquisition": [
    "Paid Advertising (Facebook/Google Ads)",
    "ASO (App Store Optimization)",
    "Growth Hacking",
    "Affiliate Marketing",
    "Retargeting",
    "CAC/LTV Optimization"
  ]
};
