// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6kC94f_bsxr4-W8SL3Y5l7-dg1QmXN7g',
    appId: '1:319914538065:web:91553f8642a26bc8387470',
    messagingSenderId: '319914538065',
    projectId: 'hire4consult-c87f1',
    authDomain: 'hire4consult-c87f1.firebaseapp.com',
    storageBucket: 'hire4consult-c87f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQiZRpdKFUNBvQhCxNRSo3K-tWTgR-9o',
    appId: '1:319914538065:android:ca7ef4e4e7d91f1c387470',
    messagingSenderId: '319914538065',
    projectId: 'hire4consult-c87f1',
    storageBucket: 'hire4consult-c87f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nUNIcrazWVSh_7wwLZ-NNUJhyPNsheU',
    appId: '1:319914538065:ios:aadcf4380e240780387470',
    messagingSenderId: '319914538065',
    projectId: 'hire4consult-c87f1',
    storageBucket: 'hire4consult-c87f1.firebasestorage.app',
    iosBundleId: 'com.example.hire4consult',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4nUNIcrazWVSh_7wwLZ-NNUJhyPNsheU',
    appId: '1:319914538065:ios:aadcf4380e240780387470',
    messagingSenderId: '319914538065',
    projectId: 'hire4consult-c87f1',
    storageBucket: 'hire4consult-c87f1.firebasestorage.app',
    iosBundleId: 'com.example.hire4consult',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6kC94f_bsxr4-W8SL3Y5l7-dg1QmXN7g',
    appId: '1:319914538065:web:222d5aa3aafef1c4387470',
    messagingSenderId: '319914538065',
    projectId: 'hire4consult-c87f1',
    authDomain: 'hire4consult-c87f1.firebaseapp.com',
    storageBucket: 'hire4consult-c87f1.firebasestorage.app',
  );
}
